NAME=ft_select

all:
	gcc -lncurses ft_select.c libft/srcs*/*.c ft_printf/srcs/*.c -o $(NAME)
	./$(NAME) 123456789 23456789 3456789 456789 56789 6789 789 89 9

clean:

fclean:
	rm -rf ./$(NAME)

re: fclean all