---
nginx:
  cmd: "ls"
  numprocs: 1
  umask: '022'
  workingdir: "/Users/"
  autostart: true
  autorestart: unexpected
  exitcodes:
  - 0
  - 2
  startretries: 3
  starttime: 5
  stopsignal: TERM
  stoptime: 10
  stdout: "/Users/hugohow-choong/42/taskmaster/logs/nginx.stdout"
  stderr: "/Users/hugohow-choong/42/taskmaster/logs/nginx.stderr"
  env:
    STARTED_BY: taskmaster
    ANSWER: 42
vogsphere:
  cmd: "ls"
  numprocs: 8
  umask: '077'
  workingdir: "/Users/hugohow-choong/42/taskmaster"
  autostart: true
  autorestart: unexpected
  exitcodes: 0
  startretries: 3
  starttime: 5
  stopsignal: USR1
  stoptime: 10
  stdout: "/Users/hugohow-choong/42/taskmaster/logs/vgsworker.stdout"
  stderr: "/Users/hugohow-choong/42/taskmaster/logs/vgsworker.stderr"
